version: '3.8'

services:
  webserver:
    build: .
    container_name: nginx_ssl
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./www:/var/www/html
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
    environment:
      - DOMAIN=example.com  # Replace with your domain
      - EMAIL=contact@example.com # Replace with your email
    command: "/bin/sh -c ./start.sh"
    networks:
      - web

networks:
  web:
    driver: bridge 
